 const weathers={
  "location": {
    "name": "Tanjung Pandan",
    "region": "Bangka–Belitung Islands",
    "country": "Indonesia",
    "lat": -2.73,
    "lon": 107.63,
    "tz_id": "Asia/Jakarta",
    "localtime_epoch": 1493920226,
    "localtime": "2017-05-05 0:50"
  },
  "current": {
    "last_updated_epoch": 1493919326,
    "last_updated": "2017-05-05 00:35",
    "temp_c": 26.1,
    "temp_f": 79,
    "is_day": 0,
    "condition": {
      "text": "Clear",
      "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
      "code": 1000
    },
    "wind_mph": 3.6,
    "wind_kph": 5.8,
    "wind_degree": 123,
    "wind_dir": "ESE",
    "pressure_mb": 1012,
    "pressure_in": 30.3,
    "precip_mm": 0,
    "precip_in": 0,
    "humidity": 87,
    "cloud": 0,
    "feelslike_c": 29.7,
    "feelslike_f": 85.5,
    "vis_km": 18.4,
    "vis_miles": 11
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2017-05-05",
        "date_epoch": 1493942400,
        "day": {
          "maxtemp_c": 35.6,
          "maxtemp_f": 96.1,
          "mintemp_c": 24.2,
          "mintemp_f": 75.6,
          "avgtemp_c": 29.8,
          "avgtemp_f": 85.7,
          "maxwind_mph": 3.8,
          "maxwind_kph": 6.1,
          "totalprecip_mm": 11.4,
          "totalprecip_in": 0.45,
          "avgvis_km": 17.5,
          "avgvis_miles": 10,
          "avghumidity": 78,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.apixu.com/weather/64x64/day/113.png",
            "code": 1000
          }
        },
        "astro": {
          "sunrise": "05:46 AM",
          "sunset": "05:47 PM",
          "moonrise": "01:51 PM",
          "moonset": "01:22 AM"
        },
        "hour": [
          {
            "time_epoch": 1493917200,
            "time": "2017-05-05 00:00",
            "temp_c": 26.1,
            "temp_f": 79,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 123,
            "wind_dir": "ESE",
            "pressure_mb": 1012,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 87,
            "cloud": 0,
            "feelslike_c": 29.7,
            "feelslike_f": 85.5,
            "windchill_c": 26.1,
            "windchill_f": 79,
            "heatindex_c": 29.7,
            "heatindex_f": 85.5,
            "dewpoint_c": 23.7,
            "dewpoint_f": 74.7,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18.4,
            "vis_miles": 11
          },
          {
            "time_epoch": 1493920800,
            "time": "2017-05-05 01:00",
            "temp_c": 24.9,
            "temp_f": 76.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 124,
            "wind_dir": "SE",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 87,
            "cloud": 0,
            "feelslike_c": 27.4,
            "feelslike_f": 81.3,
            "windchill_c": 24.9,
            "windchill_f": 76.8,
            "heatindex_c": 27.4,
            "heatindex_f": 81.3,
            "dewpoint_c": 22.6,
            "dewpoint_f": 72.7,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18,
            "vis_miles": 11
          },
          {
            "time_epoch": 1493924400,
            "time": "2017-05-05 02:00",
            "temp_c": 24.7,
            "temp_f": 76.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 120,
            "wind_dir": "ESE",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 87,
            "cloud": 0,
            "feelslike_c": 27.2,
            "feelslike_f": 81,
            "windchill_c": 24.7,
            "windchill_f": 76.5,
            "heatindex_c": 27.2,
            "heatindex_f": 81,
            "dewpoint_c": 22.5,
            "dewpoint_f": 72.5,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 17.3,
            "vis_miles": 10
          },
          {
            "time_epoch": 1493928000,
            "time": "2017-05-05 03:00",
            "temp_c": 24.6,
            "temp_f": 76.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 117,
            "wind_dir": "ESE",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 87,
            "cloud": 0,
            "feelslike_c": 26.9,
            "feelslike_f": 80.4,
            "windchill_c": 24.6,
            "windchill_f": 76.3,
            "heatindex_c": 26.9,
            "heatindex_f": 80.4,
            "dewpoint_c": 22.3,
            "dewpoint_f": 72.1,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 16.6,
            "vis_miles": 10
          },
          {
            "time_epoch": 1493931600,
            "time": "2017-05-05 04:00",
            "temp_c": 24.4,
            "temp_f": 75.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 113,
            "wind_dir": "ESE",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 88,
            "cloud": 0,
            "feelslike_c": 26.7,
            "feelslike_f": 80.1,
            "windchill_c": 24.4,
            "windchill_f": 75.9,
            "heatindex_c": 26.7,
            "heatindex_f": 80.1,
            "dewpoint_c": 22.2,
            "dewpoint_f": 72,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 15.9,
            "vis_miles": 9
          },
          {
            "time_epoch": 1493935200,
            "time": "2017-05-05 05:00",
            "temp_c": 25.6,
            "temp_f": 78.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 105,
            "wind_dir": "ESE",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 86,
            "cloud": 0,
            "feelslike_c": 28.6,
            "feelslike_f": 83.5,
            "windchill_c": 25.6,
            "windchill_f": 78.1,
            "heatindex_c": 28.6,
            "heatindex_f": 83.5,
            "dewpoint_c": 23,
            "dewpoint_f": 73.4,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 16.8,
            "vis_miles": 10
          },
          {
            "time_epoch": 1493938800,
            "time": "2017-05-05 06:00",
            "temp_c": 26.7,
            "temp_f": 80.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.apixu.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.9,
            "wind_kph": 4.7,
            "wind_degree": 97,
            "wind_dir": "E",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 84,
            "cloud": 0,
            "feelslike_c": 30.6,
            "feelslike_f": 87.1,
            "windchill_c": 26.7,
            "windchill_f": 80.1,
            "heatindex_c": 30.6,
            "heatindex_f": 87.1,
            "dewpoint_c": 23.8,
            "dewpoint_f": 74.8,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 17.7,
            "vis_miles": 10
          },
          {
            "time_epoch": 1493942400,
            "time": "2017-05-05 07:00",
            "temp_c": 27.9,
            "temp_f": 82.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.apixu.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.9,
            "wind_kph": 4.7,
            "wind_degree": 89,
            "wind_dir": "E",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 82,
            "cloud": 0,
            "feelslike_c": 32.5,
            "feelslike_f": 90.5,
            "windchill_c": 27.9,
            "windchill_f": 82.2,
            "heatindex_c": 32.5,
            "heatindex_f": 90.5,
            "dewpoint_c": 24.6,
            "dewpoint_f": 76.3,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18.6,
            "vis_miles": 11
          },
          {
            "time_epoch": 1493946000,
            "time": "2017-05-05 08:00",
            "temp_c": 30.5,
            "temp_f": 86.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.apixu.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.9,
            "wind_kph": 4.7,
            "wind_degree": 74,
            "wind_dir": "ENE",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 75,
            "cloud": 0,
            "feelslike_c": 37.3,
            "feelslike_f": 99.1,
            "windchill_c": 30.5,
            "windchill_f": 86.9,
            "heatindex_c": 37.3,
            "heatindex_f": 99.1,
            "dewpoint_c": 25.3,
            "dewpoint_f": 77.5,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 17.7,
            "vis_miles": 10
          },
          {
            "time_epoch": 1493949600,
            "time": "2017-05-05 09:00",
            "temp_c": 33,
            "temp_f": 91.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.apixu.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 58,
            "wind_dir": "ENE",
            "pressure_mb": 1012,
            "pressure_in": 30.4,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 68,
            "cloud": 0,
            "feelslike_c": 42.2,
            "feelslike_f": 108,
            "windchill_c": 33,
            "windchill_f": 91.4,
            "heatindex_c": 42.2,
            "heatindex_f": 108,
            "dewpoint_c": 26,
            "dewpoint_f": 78.8,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 16.8,
            "vis_miles": 10
          },
          {
            "time_epoch": 1493953200,
            "time": "2017-05-05 10:00",
            "temp_c": 35.6,
            "temp_f": 96.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.apixu.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 43,
            "wind_dir": "NE",
            "pressure_mb": 1012,
            "pressure_in": 30.4,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 60,
            "cloud": 0,
            "feelslike_c": 47,
            "feelslike_f": 116.6,
            "windchill_c": 35.6,
            "windchill_f": 96.1,
            "heatindex_c": 47,
            "heatindex_f": 116.6,
            "dewpoint_c": 26.7,
            "dewpoint_f": 80.1,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 15.9,
            "vis_miles": 9
          },
          {
            "time_epoch": 1493956800,
            "time": "2017-05-05 11:00",
            "temp_c": 35,
            "temp_f": 95,
            "is_day": 1,
            "condition": {
              "text": "Moderate or heavy rain shower",
              "icon": "//cdn.apixu.com/weather/64x64/day/356.png",
              "code": 1243
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 132,
            "wind_dir": "SE",
            "pressure_mb": 1012,
            "pressure_in": 30.3,
            "precip_mm": 2,
            "precip_in": 0.08,
            "humidity": 64,
            "cloud": 9,
            "feelslike_c": 46.8,
            "feelslike_f": 116.2,
            "windchill_c": 35,
            "windchill_f": 95,
            "heatindex_c": 46.8,
            "heatindex_f": 116.2,
            "dewpoint_c": 27.2,
            "dewpoint_f": 81,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 16,
            "vis_miles": 9
          },
          {
            "time_epoch": 1493960400,
            "time": "2017-05-05 12:00",
            "temp_c": 34.4,
            "temp_f": 93.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.apixu.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 221,
            "wind_dir": "SW",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 3.9,
            "precip_in": 0.15,
            "humidity": 68,
            "cloud": 19,
            "feelslike_c": 46.6,
            "feelslike_f": 115.9,
            "windchill_c": 34.4,
            "windchill_f": 93.9,
            "heatindex_c": 46.6,
            "heatindex_f": 115.9,
            "dewpoint_c": 27.6,
            "dewpoint_f": 81.7,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 16.2,
            "vis_miles": 10
          },
          {
            "time_epoch": 1493964000,
            "time": "2017-05-05 13:00",
            "temp_c": 33.8,
            "temp_f": 92.8,
            "is_day": 1,
            "condition": {
              "text": "Moderate or heavy rain shower",
              "icon": "//cdn.apixu.com/weather/64x64/day/356.png",
              "code": 1243
            },
            "wind_mph": 2,
            "wind_kph": 3.2,
            "wind_degree": 310,
            "wind_dir": "NW",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 5.9,
            "precip_in": 0.23,
            "humidity": 72,
            "cloud": 28,
            "feelslike_c": 46.4,
            "feelslike_f": 115.5,
            "windchill_c": 33.8,
            "windchill_f": 92.8,
            "heatindex_c": 46.4,
            "heatindex_f": 115.5,
            "dewpoint_c": 28.1,
            "dewpoint_f": 82.6,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "vis_km": 16.3,
            "vis_miles": 10
          },
          {
            "time_epoch": 1493967600,
            "time": "2017-05-05 14:00",
            "temp_c": 33.6,
            "temp_f": 92.5,
            "is_day": 1,
            "condition": {
              "text": "Moderate or heavy rain shower",
              "icon": "//cdn.apixu.com/weather/64x64/day/356.png",
              "code": 1243
            },
            "wind_mph": 1.8,
            "wind_kph": 2.9,
            "wind_degree": 225,
            "wind_dir": "SW",
            "pressure_mb": 1010,
            "pressure_in": 30.3,
            "precip_mm": 5.8,
            "precip_in": 0.23,
            "humidity": 72,
            "cloud": 36,
            "feelslike_c": 45.7,
            "feelslike_f": 114.3,
            "windchill_c": 33.6,
            "windchill_f": 92.5,
            "heatindex_c": 45.7,
            "heatindex_f": 114.3,
            "dewpoint_c": 27.9,
            "dewpoint_f": 82.2,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "vis_km": 16.7,
            "vis_miles": 10
          },
          {
            "time_epoch": 1493971200,
            "time": "2017-05-05 15:00",
            "temp_c": 33.5,
            "temp_f": 92.3,
            "is_day": 1,
            "condition": {
              "text": "Moderate or heavy rain shower",
              "icon": "//cdn.apixu.com/weather/64x64/day/356.png",
              "code": 1243
            },
            "wind_mph": 1.6,
            "wind_kph": 2.5,
            "wind_degree": 140,
            "wind_dir": "SE",
            "pressure_mb": 1010,
            "pressure_in": 30.3,
            "precip_mm": 5.6,
            "precip_in": 0.22,
            "humidity": 72,
            "cloud": 45,
            "feelslike_c": 45.1,
            "feelslike_f": 113.2,
            "windchill_c": 33.4,
            "windchill_f": 92.1,
            "heatindex_c": 45.1,
            "heatindex_f": 113.2,
            "dewpoint_c": 27.7,
            "dewpoint_f": 81.9,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "vis_km": 17.2,
            "vis_miles": 10
          },
          {
            "time_epoch": 1493974800,
            "time": "2017-05-05 16:00",
            "temp_c": 33.3,
            "temp_f": 91.9,
            "is_day": 1,
            "condition": {
              "text": "Moderate or heavy rain shower",
              "icon": "//cdn.apixu.com/weather/64x64/day/356.png",
              "code": 1243
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 55,
            "wind_dir": "NE",
            "pressure_mb": 1009,
            "pressure_in": 30.3,
            "precip_mm": 5.5,
            "precip_in": 0.22,
            "humidity": 72,
            "cloud": 53,
            "feelslike_c": 44.4,
            "feelslike_f": 111.9,
            "windchill_c": 33.2,
            "windchill_f": 91.8,
            "heatindex_c": 44.4,
            "heatindex_f": 111.9,
            "dewpoint_c": 27.5,
            "dewpoint_f": 81.5,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "vis_km": 17.6,
            "vis_miles": 10
          },
          {
            "time_epoch": 1493978400,
            "time": "2017-05-05 17:00",
            "temp_c": 32.6,
            "temp_f": 90.7,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.apixu.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 78,
            "wind_dir": "ENE",
            "pressure_mb": 1010,
            "pressure_in": 30.3,
            "precip_mm": 3.7,
            "precip_in": 0.15,
            "humidity": 75,
            "cloud": 44,
            "feelslike_c": 41.4,
            "feelslike_f": 106.5,
            "windchill_c": 32.6,
            "windchill_f": 90.7,
            "heatindex_c": 41.4,
            "heatindex_f": 106.5,
            "dewpoint_c": 26.1,
            "dewpoint_f": 79,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 17.9,
            "vis_miles": 11
          },
          {
            "time_epoch": 1493982000,
            "time": "2017-05-05 18:00",
            "temp_c": 32,
            "temp_f": 89.6,
            "is_day": 0,
            "condition": {
              "text": "Moderate or heavy rain shower",
              "icon": "//cdn.apixu.com/weather/64x64/night/356.png",
              "code": 1243
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 102,
            "wind_dir": "ESE",
            "pressure_mb": 1010,
            "pressure_in": 30.3,
            "precip_mm": 1.9,
            "precip_in": 0.07,
            "humidity": 79,
            "cloud": 35,
            "feelslike_c": 38.3,
            "feelslike_f": 100.9,
            "windchill_c": 31.9,
            "windchill_f": 89.4,
            "heatindex_c": 38.3,
            "heatindex_f": 100.9,
            "dewpoint_c": 24.7,
            "dewpoint_f": 76.5,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18.1,
            "vis_miles": 11
          },
          {
            "time_epoch": 1493985600,
            "time": "2017-05-05 19:00",
            "temp_c": 31.3,
            "temp_f": 88.3,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.apixu.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 126,
            "wind_dir": "SE",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 82,
            "cloud": 26,
            "feelslike_c": 35.3,
            "feelslike_f": 95.5,
            "windchill_c": 31.3,
            "windchill_f": 88.3,
            "heatindex_c": 35.3,
            "heatindex_f": 95.5,
            "dewpoint_c": 23.3,
            "dewpoint_f": 73.9,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18.4,
            "vis_miles": 11
          },
          {
            "time_epoch": 1493989200,
            "time": "2017-05-05 20:00",
            "temp_c": 30,
            "temp_f": 86,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2,
            "wind_kph": 3.2,
            "wind_degree": 118,
            "wind_dir": "ESE",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 83,
            "cloud": 17,
            "feelslike_c": 33.6,
            "feelslike_f": 92.5,
            "windchill_c": 30,
            "windchill_f": 86,
            "heatindex_c": 33.6,
            "heatindex_f": 92.5,
            "dewpoint_c": 23.1,
            "dewpoint_f": 73.6,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18.7,
            "vis_miles": 11
          },
          {
            "time_epoch": 1493992800,
            "time": "2017-05-05 21:00",
            "temp_c": 28.6,
            "temp_f": 83.5,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.apixu.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 110,
            "wind_dir": "ESE",
            "pressure_mb": 1012,
            "pressure_in": 30.4,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 84,
            "cloud": 9,
            "feelslike_c": 32,
            "feelslike_f": 89.6,
            "windchill_c": 28.6,
            "windchill_f": 83.5,
            "heatindex_c": 32,
            "heatindex_f": 89.6,
            "dewpoint_c": 23,
            "dewpoint_f": 73.4,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 19,
            "vis_miles": 11
          },
          {
            "time_epoch": 1493996400,
            "time": "2017-05-05 22:00",
            "temp_c": 27.3,
            "temp_f": 81.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 103,
            "wind_dir": "ESE",
            "pressure_mb": 1012,
            "pressure_in": 30.4,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 84,
            "cloud": 0,
            "feelslike_c": 30.3,
            "feelslike_f": 86.5,
            "windchill_c": 27.3,
            "windchill_f": 81.1,
            "heatindex_c": 30.3,
            "heatindex_f": 86.5,
            "dewpoint_c": 22.8,
            "dewpoint_f": 73,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 19.3,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494000000,
            "time": "2017-05-05 23:00",
            "temp_c": 26.5,
            "temp_f": 79.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.9,
            "wind_kph": 4.7,
            "wind_degree": 97,
            "wind_dir": "E",
            "pressure_mb": 1012,
            "pressure_in": 30.4,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 85,
            "cloud": 0,
            "feelslike_c": 29.3,
            "feelslike_f": 84.7,
            "windchill_c": 26.5,
            "windchill_f": 79.7,
            "heatindex_c": 29.3,
            "heatindex_f": 84.7,
            "dewpoint_c": 22.7,
            "dewpoint_f": 72.9,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18.7,
            "vis_miles": 11
          }
        ]
      },
      {
        "date": "2017-05-06",
        "date_epoch": 1494028800,
        "day": {
          "maxtemp_c": 35.6,
          "maxtemp_f": 96.1,
          "mintemp_c": 23.9,
          "mintemp_f": 75,
          "avgtemp_c": 29.3,
          "avgtemp_f": 84.7,
          "maxwind_mph": 6.3,
          "maxwind_kph": 10.1,
          "totalprecip_mm": 5.4,
          "totalprecip_in": 0.21,
          "avgvis_km": 17.6,
          "avgvis_miles": 10,
          "avghumidity": 77,
          "condition": {
            "text": "Patchy rain possible",
            "icon": "//cdn.apixu.com/weather/64x64/day/176.png",
            "code": 1063
          }
        },
        "astro": {
          "sunrise": "05:46 AM",
          "sunset": "05:47 PM",
          "moonrise": "02:36 PM",
          "moonset": "02:10 AM"
        },
        "hour": [
          {
            "time_epoch": 1494003600,
            "time": "2017-05-06 00:00",
            "temp_c": 25.7,
            "temp_f": 78.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 92,
            "wind_dir": "E",
            "pressure_mb": 1012,
            "pressure_in": 30.4,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 86,
            "cloud": 0,
            "feelslike_c": 28.4,
            "feelslike_f": 83.1,
            "windchill_c": 25.7,
            "windchill_f": 78.3,
            "heatindex_c": 28.4,
            "heatindex_f": 83.1,
            "dewpoint_c": 22.7,
            "dewpoint_f": 72.9,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494007200,
            "time": "2017-05-06 01:00",
            "temp_c": 24.9,
            "temp_f": 76.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 86,
            "wind_dir": "E",
            "pressure_mb": 1012,
            "pressure_in": 30.4,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 87,
            "cloud": 0,
            "feelslike_c": 27.4,
            "feelslike_f": 81.3,
            "windchill_c": 24.9,
            "windchill_f": 76.8,
            "heatindex_c": 27.4,
            "heatindex_f": 81.3,
            "dewpoint_c": 22.6,
            "dewpoint_f": 72.7,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 17.4,
            "vis_miles": 10
          },
          {
            "time_epoch": 1494010800,
            "time": "2017-05-06 02:00",
            "temp_c": 24.7,
            "temp_f": 76.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 88,
            "wind_dir": "E",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 87,
            "cloud": 0,
            "feelslike_c": 27.1,
            "feelslike_f": 80.8,
            "windchill_c": 24.7,
            "windchill_f": 76.5,
            "heatindex_c": 27.1,
            "heatindex_f": 80.8,
            "dewpoint_c": 22.4,
            "dewpoint_f": 72.3,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 16.9,
            "vis_miles": 10
          },
          {
            "time_epoch": 1494014400,
            "time": "2017-05-06 03:00",
            "temp_c": 24.4,
            "temp_f": 75.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2,
            "wind_kph": 3.2,
            "wind_degree": 91,
            "wind_dir": "E",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 88,
            "cloud": 0,
            "feelslike_c": 26.8,
            "feelslike_f": 80.2,
            "windchill_c": 24.4,
            "windchill_f": 75.9,
            "heatindex_c": 26.8,
            "heatindex_f": 80.2,
            "dewpoint_c": 22.3,
            "dewpoint_f": 72.1,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 16.5,
            "vis_miles": 10
          },
          {
            "time_epoch": 1494018000,
            "time": "2017-05-06 04:00",
            "temp_c": 24.2,
            "temp_f": 75.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2,
            "wind_kph": 3.2,
            "wind_degree": 93,
            "wind_dir": "E",
            "pressure_mb": 1010,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 88,
            "cloud": 0,
            "feelslike_c": 26.5,
            "feelslike_f": 79.7,
            "windchill_c": 24.2,
            "windchill_f": 75.6,
            "heatindex_c": 26.5,
            "heatindex_f": 79.7,
            "dewpoint_c": 22.1,
            "dewpoint_f": 71.8,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 16,
            "vis_miles": 9
          },
          {
            "time_epoch": 1494021600,
            "time": "2017-05-06 05:00",
            "temp_c": 25.8,
            "temp_f": 78.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.apixu.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2,
            "wind_kph": 3.2,
            "wind_degree": 85,
            "wind_dir": "E",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 85,
            "cloud": 0,
            "feelslike_c": 29.2,
            "feelslike_f": 84.6,
            "windchill_c": 25.8,
            "windchill_f": 78.4,
            "heatindex_c": 29.2,
            "heatindex_f": 84.6,
            "dewpoint_c": 23.1,
            "dewpoint_f": 73.6,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 16.2,
            "vis_miles": 10
          },
          {
            "time_epoch": 1494025200,
            "time": "2017-05-06 06:00",
            "temp_c": 27.5,
            "temp_f": 81.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.apixu.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 1.8,
            "wind_kph": 2.9,
            "wind_degree": 78,
            "wind_dir": "ENE",
            "pressure_mb": 1012,
            "pressure_in": 30.3,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 82,
            "cloud": 0,
            "feelslike_c": 32,
            "feelslike_f": 89.6,
            "windchill_c": 27.5,
            "windchill_f": 81.5,
            "heatindex_c": 32,
            "heatindex_f": 89.6,
            "dewpoint_c": 24.1,
            "dewpoint_f": 75.4,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 16.4,
            "vis_miles": 10
          },
          {
            "time_epoch": 1494028800,
            "time": "2017-05-06 07:00",
            "temp_c": 29.1,
            "temp_f": 84.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.apixu.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 1.8,
            "wind_kph": 2.9,
            "wind_degree": 70,
            "wind_dir": "ENE",
            "pressure_mb": 1012,
            "pressure_in": 30.4,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 79,
            "cloud": 0,
            "feelslike_c": 34.7,
            "feelslike_f": 94.5,
            "windchill_c": 29.1,
            "windchill_f": 84.4,
            "heatindex_c": 34.7,
            "heatindex_f": 94.5,
            "dewpoint_c": 25.1,
            "dewpoint_f": 77.2,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 16.6,
            "vis_miles": 10
          },
          {
            "time_epoch": 1494032400,
            "time": "2017-05-06 08:00",
            "temp_c": 31.3,
            "temp_f": 88.3,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.apixu.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 51,
            "wind_dir": "NE",
            "pressure_mb": 1013,
            "pressure_in": 30.4,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 72,
            "cloud": 6,
            "feelslike_c": 38.5,
            "feelslike_f": 101.3,
            "windchill_c": 31.3,
            "windchill_f": 88.3,
            "heatindex_c": 38.5,
            "heatindex_f": 101.3,
            "dewpoint_c": 25.4,
            "dewpoint_f": 77.7,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 17.1,
            "vis_miles": 10
          },
          {
            "time_epoch": 1494036000,
            "time": "2017-05-06 09:00",
            "temp_c": 33.4,
            "temp_f": 92.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.apixu.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.9,
            "wind_kph": 4.7,
            "wind_degree": 31,
            "wind_dir": "NNE",
            "pressure_mb": 1013,
            "pressure_in": 30.4,
            "precip_mm": 0.2,
            "precip_in": 0.01,
            "humidity": 65,
            "cloud": 13,
            "feelslike_c": 42.2,
            "feelslike_f": 108,
            "windchill_c": 33.4,
            "windchill_f": 92.1,
            "heatindex_c": 42.2,
            "heatindex_f": 108,
            "dewpoint_c": 25.8,
            "dewpoint_f": 78.4,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 17.5,
            "vis_miles": 10
          },
          {
            "time_epoch": 1494039600,
            "time": "2017-05-06 10:00",
            "temp_c": 35.6,
            "temp_f": 96.1,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.apixu.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 11,
            "wind_dir": "NNE",
            "pressure_mb": 1014,
            "pressure_in": 30.4,
            "precip_mm": 0.2,
            "precip_in": 0.01,
            "humidity": 58,
            "cloud": 19,
            "feelslike_c": 46,
            "feelslike_f": 114.8,
            "windchill_c": 35.6,
            "windchill_f": 96.1,
            "heatindex_c": 46,
            "heatindex_f": 114.8,
            "dewpoint_c": 26.1,
            "dewpoint_f": 79,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494043200,
            "time": "2017-05-06 11:00",
            "temp_c": 34.5,
            "temp_f": 94.1,
            "is_day": 1,
            "condition": {
              "text": "Moderate or heavy rain shower",
              "icon": "//cdn.apixu.com/weather/64x64/day/356.png",
              "code": 1243
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 120,
            "wind_dir": "ESE",
            "pressure_mb": 1013,
            "pressure_in": 30.4,
            "precip_mm": 1.1,
            "precip_in": 0.04,
            "humidity": 63,
            "cloud": 20,
            "feelslike_c": 44.8,
            "feelslike_f": 112.6,
            "windchill_c": 34.5,
            "windchill_f": 94.1,
            "heatindex_c": 44.8,
            "heatindex_f": 112.6,
            "dewpoint_c": 26.5,
            "dewpoint_f": 79.7,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 17.9,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494046800,
            "time": "2017-05-06 12:00",
            "temp_c": 33.5,
            "temp_f": 92.3,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.apixu.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 230,
            "wind_dir": "SW",
            "pressure_mb": 1012,
            "pressure_in": 30.4,
            "precip_mm": 2.1,
            "precip_in": 0.08,
            "humidity": 69,
            "cloud": 21,
            "feelslike_c": 43.7,
            "feelslike_f": 110.7,
            "windchill_c": 33.5,
            "windchill_f": 92.3,
            "heatindex_c": 43.7,
            "heatindex_f": 110.7,
            "dewpoint_c": 26.8,
            "dewpoint_f": 80.2,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "vis_km": 17.9,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494050400,
            "time": "2017-05-06 13:00",
            "temp_c": 32.4,
            "temp_f": 90.3,
            "is_day": 1,
            "condition": {
              "text": "Moderate or heavy rain shower",
              "icon": "//cdn.apixu.com/weather/64x64/day/356.png",
              "code": 1243
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 339,
            "wind_dir": "NNW",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 3,
            "precip_in": 0.12,
            "humidity": 74,
            "cloud": 23,
            "feelslike_c": 42.5,
            "feelslike_f": 108.5,
            "windchill_c": 32.4,
            "windchill_f": 90.3,
            "heatindex_c": 42.5,
            "heatindex_f": 108.5,
            "dewpoint_c": 27.2,
            "dewpoint_f": 81,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "vis_km": 17.8,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494054000,
            "time": "2017-05-06 14:00",
            "temp_c": 32.5,
            "temp_f": 90.5,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.apixu.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 5.6,
            "wind_kph": 9,
            "wind_degree": 344,
            "wind_dir": "NNW",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 2.7,
            "precip_in": 0.11,
            "humidity": 73,
            "cloud": 25,
            "feelslike_c": 42.4,
            "feelslike_f": 108.3,
            "windchill_c": 32.5,
            "windchill_f": 90.5,
            "heatindex_c": 42.4,
            "heatindex_f": 108.3,
            "dewpoint_c": 26.9,
            "dewpoint_f": 80.4,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "vis_km": 18,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494057600,
            "time": "2017-05-06 15:00",
            "temp_c": 32.7,
            "temp_f": 90.9,
            "is_day": 1,
            "condition": {
              "text": "Moderate or heavy rain shower",
              "icon": "//cdn.apixu.com/weather/64x64/day/356.png",
              "code": 1243
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 350,
            "wind_dir": "N",
            "pressure_mb": 1010,
            "pressure_in": 30.3,
            "precip_mm": 2.4,
            "precip_in": 0.09,
            "humidity": 71,
            "cloud": 28,
            "feelslike_c": 42.2,
            "feelslike_f": 108,
            "windchill_c": 32.7,
            "windchill_f": 90.9,
            "heatindex_c": 42.2,
            "heatindex_f": 108,
            "dewpoint_c": 26.7,
            "dewpoint_f": 80.1,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "vis_km": 18.2,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494061200,
            "time": "2017-05-06 16:00",
            "temp_c": 32.8,
            "temp_f": 91,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.apixu.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 355,
            "wind_dir": "N",
            "pressure_mb": 1009,
            "pressure_in": 30.3,
            "precip_mm": 2.1,
            "precip_in": 0.08,
            "humidity": 69,
            "cloud": 31,
            "feelslike_c": 42.1,
            "feelslike_f": 107.8,
            "windchill_c": 32.8,
            "windchill_f": 91,
            "heatindex_c": 42.1,
            "heatindex_f": 107.8,
            "dewpoint_c": 26.4,
            "dewpoint_f": 79.5,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "vis_km": 18.4,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494064800,
            "time": "2017-05-06 17:00",
            "temp_c": 31.8,
            "temp_f": 89.2,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.apixu.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 244,
            "wind_dir": "WSW",
            "pressure_mb": 1010,
            "pressure_in": 30.3,
            "precip_mm": 1.4,
            "precip_in": 0.06,
            "humidity": 72,
            "cloud": 36,
            "feelslike_c": 39.3,
            "feelslike_f": 102.7,
            "windchill_c": 31.8,
            "windchill_f": 89.2,
            "heatindex_c": 39.3,
            "heatindex_f": 102.7,
            "dewpoint_c": 25,
            "dewpoint_f": 77,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18.3,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494068400,
            "time": "2017-05-06 18:00",
            "temp_c": 30.8,
            "temp_f": 87.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.apixu.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 134,
            "wind_dir": "SE",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0.7,
            "precip_in": 0.03,
            "humidity": 74,
            "cloud": 41,
            "feelslike_c": 36.6,
            "feelslike_f": 97.9,
            "windchill_c": 30.8,
            "windchill_f": 87.4,
            "heatindex_c": 36.6,
            "heatindex_f": 97.9,
            "dewpoint_c": 23.5,
            "dewpoint_f": 74.3,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18.2,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494072000,
            "time": "2017-05-06 19:00",
            "temp_c": 29.8,
            "temp_f": 85.6,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.apixu.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 23,
            "wind_dir": "NNE",
            "pressure_mb": 1011,
            "pressure_in": 30.3,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 77,
            "cloud": 46,
            "feelslike_c": 33.8,
            "feelslike_f": 92.8,
            "windchill_c": 29.8,
            "windchill_f": 85.6,
            "heatindex_c": 33.8,
            "heatindex_f": 92.8,
            "dewpoint_c": 22.1,
            "dewpoint_f": 71.8,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18.1,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494075600,
            "time": "2017-05-06 20:00",
            "temp_c": 28.3,
            "temp_f": 82.9,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.apixu.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 20,
            "wind_dir": "NNE",
            "pressure_mb": 1012,
            "pressure_in": 30.4,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 78,
            "cloud": 42,
            "feelslike_c": 31.7,
            "feelslike_f": 89.1,
            "windchill_c": 28.3,
            "windchill_f": 82.9,
            "heatindex_c": 31.7,
            "heatindex_f": 89.1,
            "dewpoint_c": 22,
            "dewpoint_f": 71.6,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18.3,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494079200,
            "time": "2017-05-06 21:00",
            "temp_c": 26.9,
            "temp_f": 80.4,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.apixu.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 18,
            "wind_dir": "NNE",
            "pressure_mb": 1013,
            "pressure_in": 30.4,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 79,
            "cloud": 38,
            "feelslike_c": 29.7,
            "feelslike_f": 85.5,
            "windchill_c": 26.9,
            "windchill_f": 80.4,
            "heatindex_c": 29.7,
            "heatindex_f": 85.5,
            "dewpoint_c": 21.8,
            "dewpoint_f": 71.2,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18.4,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494082800,
            "time": "2017-05-06 22:00",
            "temp_c": 25.4,
            "temp_f": 77.7,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.apixu.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 15,
            "wind_dir": "NNE",
            "pressure_mb": 1013,
            "pressure_in": 30.4,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 33,
            "feelslike_c": 27.6,
            "feelslike_f": 81.7,
            "windchill_c": 25.4,
            "windchill_f": 77.7,
            "heatindex_c": 27.6,
            "heatindex_f": 81.7,
            "dewpoint_c": 21.7,
            "dewpoint_f": 71.1,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18.6,
            "vis_miles": 11
          },
          {
            "time_epoch": 1494086400,
            "time": "2017-05-06 23:00",
            "temp_c": 25.1,
            "temp_f": 77.2,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.apixu.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 2.9,
            "wind_kph": 4.7,
            "wind_degree": 12,
            "wind_dir": "NNE",
            "pressure_mb": 1013,
            "pressure_in": 30.4,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 31,
            "feelslike_c": 27.3,
            "feelslike_f": 81.1,
            "windchill_c": 25.1,
            "windchill_f": 77.2,
            "heatindex_c": 27.3,
            "heatindex_f": 81.1,
            "dewpoint_c": 21.6,
            "dewpoint_f": 70.9,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "vis_km": 18.8,
            "vis_miles": 11
          }
        ]
      }
    ]
  }
}
export default weathers
